// Emits design/tokens.css and design/theme-dark.css from design/tokens.json (ui/shared) so every stylesheet references
// CSS custom properties and the JSON stays the single source of truth for the visual system.
//
// tokens.css holds the light theme plus everything theme-independent (fonts, radii, layout, type scale). Both apps
// import it. theme-dark.css redefines the color, pane, and shadow variables for the dark theme; only the public site
// imports it, so the admin app (PrimeVue Aura, light only) is unaffected.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../design/tokens.json");
const lightTarget = resolve(here, "../design/tokens.css");
const darkTarget = resolve(here, "../design/theme-dark.css");
const tokens = JSON.parse(readFileSync(source, "utf8"));

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const banner = "/* Generated by scripts/build-tokens.mjs from tokens.json. Do not edit by hand. */";

function colorLines(colors, prefix, indent) {
	return Object.entries(colors).map(([name, value]) => `${indent}--${prefix}-${kebab(name)}: ${value};`);
}

function shadowLines(shadows, indent) {
	return Object.entries(shadows).map(([name, value]) => `${indent}--shadow-${kebab(name)}: ${value};`);
}

// --- tokens.css (light + theme-independent) -------------------------------------------------------------------

const lines = [];

lines.push(banner);
lines.push(":root {");
lines.push("\tcolor-scheme: light;");
lines.push("");
lines.push("\t/* fonts */");

// Self-hosted variable fonts from @fontsource-variable register as "<Family> Variable"; the design's family names
// stay in the stack as fallbacks for environments that load the static faces instead.
const variableFamilies = { sans: "'IBM Plex Sans Variable', ", serif: "'Newsreader Variable', " };

for (const [name, value] of Object.entries(tokens.font)) {
	if (typeof value === "string" && !name.endsWith("Url")) {
		lines.push(`\t--font-${kebab(name)}: ${variableFamilies[name] ?? ""}${value};`);
	}
}

lines.push("");
lines.push("\t/* light theme colors */");
lines.push(...colorLines(tokens.color.light, "color", "\t"));

lines.push("");
lines.push("\t/* dark pane (machine-truth content) colors */");
lines.push(...colorLines(tokens.color.pane, "pane", "\t"));

lines.push("");
lines.push("\t/* shadows */");
lines.push(...shadowLines(tokens.shadow.light, "\t"));

lines.push("");
lines.push("\t/* radii */");

const radiusDefaults = { chip: "4px", control: "6px", card: "8px", dialog: "12px", sheet: "14px", pill: "15px" };

for (const [name, value] of Object.entries(tokens.radius)) {
	const px = /^\d+px$/.test(value) ? value : radiusDefaults[name];
	lines.push(`\t--radius-${kebab(name)}: ${px};`);
}

lines.push("");
lines.push("\t/* layout */");
lines.push("\t--header-height: 60px;");
lines.push("\t--header-height-mobile: 56px;");
lines.push("\t--page-pad-x: 48px;");
lines.push("\t--rail-width: 248px;");
lines.push("\t--pane-width: 540px;");
lines.push("\t--touch-target: 44px;");
lines.push("\t--card-pad: 16px 18px;");
lines.push("\t--breakpoint-mobile: 768px;");

lines.push("");
lines.push("\t/* type scale */");
lines.push("\t--text-body: 15px;");
lines.push("\t--leading-body: 1.6;");
lines.push("\t--text-small: 14px;");
lines.push("\t--text-meta: 13px;");
lines.push("\t--text-label: 12px;");
lines.push("\t--text-symbol-title: 38px;");
lines.push("\t--text-symbol-title-mobile: 28px;");
lines.push("\t--text-summary: 22px;");
lines.push("\t--text-summary-mobile: 18px;");
lines.push("\t--text-page-title: 34px;");
lines.push("\t--text-h2: 17px;");
lines.push("\t--text-code: 13.5px;");
lines.push("\t--leading-code: 1.65;");
lines.push("}");
lines.push("");

writeFileSync(lightTarget, lines.join("\n") + "\n");
console.log(`tokens.css written (${lines.length} lines)`);

// --- theme-dark.css --------------------------------------------------------------------------------------------
// The same block is emitted twice: once for an explicit choice (data-theme="dark") and once for the system
// preference when the reader has not chosen (no data-theme="light"). Duplicating generated CSS beats a runtime
// dependency on JavaScript for the system case.

const darkBody = [
	"\tcolor-scheme: dark;",
	"",
	"\t/* dark theme colors */",
	...colorLines(tokens.color.dark, "color", "\t"),
	"",
	"\t/* pane, a step darker than the ground so it still reads as its own surface */",
	...colorLines(tokens.color.paneDark, "pane", "\t"),
	"",
	"\t/* shadows */",
	...shadowLines(tokens.shadow.dark, "\t"),
];

const dark = [];

dark.push(banner);
dark.push("/* Dark theme. Loaded by the public site only; see stores/theme.ts for how data-theme is set. */");
dark.push(':root[data-theme="dark"] {');
dark.push(...darkBody);
dark.push("}");
dark.push("");
dark.push("@media (prefers-color-scheme: dark) {");
dark.push('\t:root:not([data-theme="light"]) {');
dark.push(...darkBody.map((line) => (line ? `\t${line}` : line)));
dark.push("\t}");
dark.push("}");
dark.push("");

writeFileSync(darkTarget, dark.join("\n") + "\n");
console.log(`theme-dark.css written (${dark.length} lines)`);
