// Emits design/tokens.css from design/tokens.json (ui/shared) so every stylesheet references CSS custom properties
// and the JSON stays the single source of truth for the visual system.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../design/tokens.json");
const target = resolve(here, "../design/tokens.css");
const tokens = JSON.parse(readFileSync(source, "utf8"));

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const lines = [];

lines.push("/* Generated by scripts/build-tokens.mjs from tokens.json. Do not edit by hand. */");
lines.push(":root {");
lines.push("\t/* fonts */");

// Self-hosted variable fonts from @fontsource-variable register as "<Family> Variable"; the design's family names
// stay in the stack as fallbacks for environments that load the static faces instead.
const variableFamilies = { sans: "'IBM Plex Sans Variable', ", serif: "'Newsreader Variable', " };

for (const [name, value] of Object.entries(tokens.font)) {
	if (typeof value === "string" && !name.endsWith("Url")) {
		lines.push(`\t--font-${kebab(name)}: ${variableFamilies[name] ?? ""}${value};`);
	}
}

lines.push("");
lines.push("\t/* light theme colors */");

for (const [name, value] of Object.entries(tokens.color.light)) {
	lines.push(`\t--color-${kebab(name)}: ${value};`);
}

lines.push("");
lines.push("\t/* dark pane (machine-truth content) colors */");

for (const [name, value] of Object.entries(tokens.color.pane)) {
	lines.push(`\t--pane-${kebab(name)}: ${value};`);
}

lines.push("");
lines.push("\t/* radii */");

const radiusDefaults = { chip: "4px", control: "6px", card: "8px", dialog: "12px", sheet: "14px", pill: "15px" };

for (const [name, value] of Object.entries(tokens.radius)) {
	const px = /^\d+px$/.test(value) ? value : radiusDefaults[name];
	lines.push(`\t--radius-${kebab(name)}: ${px};`);
}

lines.push("");
lines.push("\t/* layout */");
lines.push("\t--header-height: 60px;");
lines.push("\t--header-height-mobile: 56px;");
lines.push("\t--page-pad-x: 48px;");
lines.push("\t--rail-width: 248px;");
lines.push("\t--pane-width: 540px;");
lines.push("\t--touch-target: 44px;");
lines.push("\t--card-pad: 16px 18px;");
lines.push("\t--breakpoint-mobile: 768px;");

lines.push("");
lines.push("\t/* type scale */");
lines.push("\t--text-body: 15px;");
lines.push("\t--leading-body: 1.6;");
lines.push("\t--text-small: 14px;");
lines.push("\t--text-meta: 13px;");
lines.push("\t--text-label: 12px;");
lines.push("\t--text-symbol-title: 38px;");
lines.push("\t--text-symbol-title-mobile: 28px;");
lines.push("\t--text-summary: 22px;");
lines.push("\t--text-summary-mobile: 18px;");
lines.push("\t--text-page-title: 34px;");
lines.push("\t--text-h2: 17px;");
lines.push("\t--text-code: 13.5px;");
lines.push("\t--leading-code: 1.65;");
lines.push("}");
lines.push("");

writeFileSync(target, lines.join("\n") + "\n");
console.log(`tokens.css written (${lines.length} lines)`);
